---
title: "Lab9x"
author: "Thomas Wilson"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x <- runif(1, 0, 10)  
if(x > 3) {
        y <- 9
} else {
        y <- 0
}
y

for(i in 1:10) {
        print(i)
}
x <- c("a", "b", "c", "d", "e")
for(i in 1:5) {
        print(x[i])  
}
```
```{r}
for(i in seq_along(x)) {   
        print(x[i])
}
for(letter in x) {
        print(letter)
}
for(i in 1:5) print(x[i])

x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```
```{r}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
```
```{r}
z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {
                z <- z + 5
        } else {
                z <- z - 2
        } 
}
print(z)

f <- function() {
        
}
 
class(f)  
f()
f <- function() {
        cat("I Love Bioinformatics!\n")
}
f()
f <- function(num) {
        for(i in seq_len(num)) {
                cat("I Love Bioinformatics!\n")
        }
}
f(5)
```
```{r}
f <- function(num) {
        hello <- "I Love Bioinformatics!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
meaningoflife <- f(3)

print(meaningoflife)

f <- function(num = 1) {
        hello <- "I Love Bioinformatics!\n"
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()
f(num = 2)
```

